import { useState } from 'react';
import { Button, PageHeader, rupee } from '../components/ui';
import { useStore } from '../services/store';
import { useProfile } from '../services/profile';

type Kind='purchases'|'customers'|'suppliers'|'expenses'|'wastage'|'reports'|'closing'|'settings'|'alerts';
const date=()=>new Date().toISOString().slice(0,10);

export function Operations({kind}:{kind:Kind}) {
  const {profile,updateProfile}=useProfile();
  const s=useStore(); const [first,setFirst]=useState(''); const [amount,setAmount]=useState(''); const [third,setThird]=useState(''); const [message,setMessage]=useState('');
  const save=()=>{
    if(kind==='customers'){if(!first)return setMessage('Enter a customer name.');s.mutate(x=>({...x,customers:[...x.customers,{id:`c${Date.now()}`,name:first,phone:amount,due:0,active:true}]}));return setMessage('Customer added.');}
    if(kind==='suppliers'){if(!first)return setMessage('Enter a supplier name.');s.mutate(x=>({...x,suppliers:[...x.suppliers,{id:`s${Date.now()}`,name:first,phone:amount,due:0,active:true}]}));return setMessage('Supplier added.');}
    if(kind==='expenses'){if(!first||+amount<=0)return setMessage('Enter a title and valid amount.');s.mutate(x=>({...x,expenses:[...x.expenses,{id:`e${Date.now()}`,title:first,category:third||'Other',amount:+amount,date:date(),payment:'Cash'}]}));return setMessage('Expense recorded.');}
    if(kind==='purchases'){const p=s.products.find(x=>x.id===first),sup=s.suppliers.find(x=>x.id===third),q=+amount;if(!p||!sup||q<1)return setMessage('Select a product, supplier, and quantity.');const cost=q*p.purchasePrice;s.mutate(x=>({...x,products:x.products.map(z=>z.id===p.id?{...z,stock:z.stock+q}:z),suppliers:x.suppliers.map(z=>z.id===sup.id?{...z,due:z.due+cost}:z)}));return setMessage(`Purchase saved. ${q} units added; ${rupee(cost)} supplier due.`);}
    if(kind==='wastage')return setMessage(s.addWastage({productId:first,quantity:+amount,reason:third||'Damaged',date:date()}));
    if(kind==='closing'){const expected=cashExpected(s);if(+amount<0)return setMessage('Enter actual cash.');s.mutate(x=>({...x,closings:[...(x.closings||[]),{id:`cl${Date.now()}`,date:date(),actualCash:+amount,expectedCash:expected}]}));return setMessage(`Closing saved. ${+amount===expected?'Cash matched.':`Difference: ${rupee(+amount-expected)}`}`);}
  };
  if(kind==='reports')return <Reports/>;
  if(kind==='alerts')return <><PageHeader title="Alerts" description="Live stock and expiry attention list."/><article className="card">{s.alerts.map(a=><div className="alert-row" key={a.id}><i className={a.level}/><span>{a.text}</span><button>{a.action}</button></div>)}</article></>;
  if(kind==='settings')return <><PageHeader title="Settings" description="Update details shown throughout your store dashboard."/><article className="card" style={{maxWidth:600}}><h2>Store Details</h2><div className="form-grid"><label>Store name<input value={first||profile.shopName} onChange={e=>setFirst(e.target.value)}/></label><label>Owner name<input value={amount||profile.ownerName} onChange={e=>setAmount(e.target.value)}/></label><label>Location<input value={third||profile.location} onChange={e=>setThird(e.target.value)}/></label><Button onClick={()=>{updateProfile({shopName:first||profile.shopName,ownerName:amount||profile.ownerName,location:third||profile.location});setMessage('Store details saved.')}}>Save Store Details</Button></div><hr/><h2>Reset Demo Data</h2><p>This removes local transaction changes from this browser and restores the original demo records.</p><Button onClick={()=>{if(confirm('Restore original demo data?')){s.reset();setMessage('Demo data restored.')}}}>Reset Demo Data</Button>{message&&<p>{message}</p>}</article></>;
  const title:Record<string,string>={purchases:'Purchases',customers:'Customers',suppliers:'Suppliers',expenses:'Expenses',wastage:'Wastage',closing:'Daily Closing'}; const choose=kind==='purchases'||kind==='wastage';
  return <><PageHeader title={title[kind]} description={kind==='wastage'?'Record items that are damaged, expired, spoiled, broken, or missing. Stock and loss update automatically.':'Saved locally and reflected across the dashboard.'}/><article className="card" style={{maxWidth:680}}><div className="form-grid"><label>{choose?'Product':'Name'}{choose?<select value={first} onChange={e=>setFirst(e.target.value)}><option value="">Select product</option>{s.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.stock} available</option>)}</select>:<input value={first} onChange={e=>setFirst(e.target.value)}/>}</label><label>{choose?'Quantity':kind==='expenses'||kind==='closing'?'Amount':'Phone'}<input type={choose||kind==='expenses'||kind==='closing'?'number':'text'} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{kind==='purchases'?'Supplier':kind==='wastage'?'Why are you removing it?':kind==='expenses'?'Category':'Notes'}{kind==='purchases'?<select value={third} onChange={e=>setThird(e.target.value)}><option value="">Select supplier</option>{s.suppliers.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select>:kind==='wastage'?<select value={third} onChange={e=>setThird(e.target.value)}><option value="">Choose reason</option><option>Expired</option><option>Damaged</option><option>Broken</option><option>Spoiled</option><option>Lost / Missing</option><option>Other</option></select>:<input value={third} onChange={e=>setThird(e.target.value)}/>}</label><Button onClick={save}>{kind==='closing'?'Close Day':'Save'}</Button></div>{kind==='wastage'&&<p>Use wastage only for stock you cannot sell. The system removes it from inventory and records its purchase-cost loss.</p>}{kind==='closing'&&<p>Expected cash today: <b>{rupee(cashExpected(s))}</b></p>}{message&&<p>{message}</p>}</article>{(kind==='customers'||kind==='suppliers')&&<BalanceTable kind={kind}/>}</>;
}
function cashExpected(s:ReturnType<typeof useStore>){return s.sales.filter(x=>x.payment==='Cash').reduce((n,x)=>n+x.total,0)-s.expenses.filter(x=>x.payment==='Cash').reduce((n,x)=>n+x.amount,0)}
function BalanceTable({kind}:{kind:'customers'|'suppliers'}){const s=useStore();const [id,setId]=useState('');const [amount,setAmount]=useState('');const record=()=>{const n=+amount,list=kind==='customers'?s.customers:s.suppliers,item=list.find(x=>x.id===id);if(!item||n<=0||n>item.due)return alert('Payment cannot exceed the amount due.');s.mutate(x=>({...x,[kind]: (kind==='customers'?x.customers:x.suppliers).map(q=>q.id===id?{...q,due:q.due-n}:q),payments:[...(x.payments||[]),{id:`pay${Date.now()}`,partyId:id,partyType:kind==='customers'?'customer':'supplier',amount:n,payment:'Cash',date:date()}]}));setAmount('');};const list=kind==='customers'?s.customers:s.suppliers;const balanceLabel=kind==='customers'?'Money to collect (Udhar)':'Money we need to pay';return <article className="card table-card" style={{marginTop:18}}><h2>{balanceLabel}</h2><p>{kind==='customers'?'This is the amount each customer still needs to pay your store.':'This is the amount your store still needs to pay each supplier.'}</p><div className="scroll"><table><thead><tr><th>Name</th><th>Phone</th><th>{balanceLabel}</th><th>Receive / Pay</th></tr></thead><tbody>{list.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.phone}</td><td>{rupee(x.due)}</td><td><button className="link" onClick={()=>setId(x.id)}>Select</button></td></tr>)}</tbody></table></div>{id&&<div className="form-grid" style={{marginTop:16}}><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><Button onClick={record}>Record Payment</Button></div>}</article>}
function Reports(){const s=useStore(),revenue=s.sales.reduce((n,x)=>n+x.total,0),profit=s.sales.reduce((n,x)=>n+x.profit,0),expenses=s.expenses.reduce((n,x)=>n+x.amount,0),waste=s.wastages.reduce((n,x)=>n+x.loss,0),stock=s.products.reduce((n,x)=>n+x.stock*x.purchasePrice,0);return <><PageHeader title="Reports" description="Live totals calculated from the saved store data."/><section className="kpis">{[['Revenue',revenue],['Gross Profit',profit],['Expenses',expenses],['Wastage Loss',waste],['Estimated Net Profit',profit-expenses-waste],['Inventory Value',stock]].map(([n,v])=><article className="kpi" key={String(n)}><p>{n}</p><h3>{rupee(v as number)}</h3></article>)}</section></>}
